[tasks.release]
command = "cargo"
args = ["build", "--release"]

[tasks.linux-release]
description = "Builds a static binary for Linux using MUSL"
script = [
  "rustup target add x86_64-unknown-linux-musl",
  "cargo build --release --target x86_64-unknown-linux-musl",
]

[tasks.windows-release]
description = "Builds a 64-bit Windows executable"
script = [
  "rustup target add x86_64-pc-windows-msvc",
  "cargo build --release --target x86_64-pc-windows-msvc",
]

[tasks.mac-universal-release]
description = "Builds a universal binary for Intel and Apple Silicon"
script = [
  "rustup target add aarch64-apple-darwin x86_64-apple-darwin",
  "cargo build --release --target aarch64-apple-darwin",
  "cargo build --release --target x86_64-apple-darwin",
  "lipo -create -output nexusintellicore target/aarch64-apple-darwin/release/nexusintellicore target/x86_64-apple-darwin/release/nexusintellicore",
]
